/**
 * Contractor Plan Template
 *
 * The markdown template structure for work plans
 * generated by Contractor.
 */

export const CONTRACTOR_PLAN_TEMPLATE = `## Plan Structure

Generate plan to: \\\`.groundcontrol/plans/{name}.md\\\`

\\\`\\\`\\\`markdown
# {Plan Title}

## TL;DR

> **Quick Summary**: [1-2 sentences capturing the core objective and approach]
>
> **Deliverables**: [Bullet list of concrete outputs]
> - [Output 1]
> - [Output 2]
>
> **Estimated Effort**: [Quick | Short | Medium | Large | XL]
> **Parallel Execution**: [YES - N waves | NO - sequential]
> **Critical Path**: [Task X → Task Y → Task Z]

---

## Context

### Original Request
[User's initial description]

### Interview Summary
**Key Discussions**:
- [Point 1]: [User's decision/preference]
- [Point 2]: [Agreed approach]

**Research Findings**:
- [Finding 1]: [Implication]
- [Finding 2]: [Recommendation]

### PreFlight Review
**Identified Gaps** (addressed):
- [Gap 1]: [How resolved]
- [Gap 2]: [How resolved]

---

## Work Objectives

### Core Objective
[1-2 sentences: what we're achieving]

### Concrete Deliverables
- [Exact file/endpoint/feature]

### Definition of Done
- [ ] [Verifiable condition with command]

### Must Have
- [Non-negotiable requirement]

### Must NOT Have (Guardrails)
- [Explicit exclusion from PreFlight review]
- [AI slop pattern to avoid]
- [Scope boundary]

---

## Verification Strategy (MANDATORY)

> **ZERO HUMAN INTERVENTION** — ALL verification is agent-executed. No exceptions.
> Acceptance criteria requiring "user manually tests/confirms" are FORBIDDEN.

### Test Decision
- **Infrastructure exists**: [YES/NO]
- **Automated tests**: [TDD / Tests-after / None]
- **Framework**: [bun test / vitest / jest / pytest / none]
- **If TDD**: Each task follows RED (failing test) → GREEN (minimal impl) → REFACTOR

### QA Policy
Every task MUST include agent-executed QA scenarios (see TODO template below).
Evidence saved to \\\`.groundcontrol/evidence/task-{N}-{scenario-slug}.{ext}\\\`.

- **Frontend/UI**: Use Playwright (playwright skill) — Navigate, interact, assert DOM, screenshot
- **TUI/CLI**: Use interactive_bash (tmux) — Run command, send keystrokes, validate output
- **API/Backend**: Use Bash (curl) — Send requests, assert status + response fields
- **Library/Module**: Use Bash (bun/node REPL) — Import, call functions, compare output

---

## Execution Strategy

### Parallel Execution Waves

> Maximize throughput by grouping independent tasks into parallel waves.
> Each wave completes before the next begins.
> Target: 5-8 tasks per wave. Fewer than 3 per wave (except final) = under-splitting.

Wave 1: [foundation tasks]
Wave 2: [dependent tasks]
...
Wave FINAL: [verification — 4 parallel agents, ALL must APPROVE]

### Dependency Matrix
[Full matrix for ALL tasks]

### Agent Dispatch Summary
[Wave → task count → categories]

---

## TODOs

> Implementation + Test = ONE Task. Never separate.
> EVERY task MUST have: Recommended Agent Profile + Parallelization info + QA Scenarios.
> **A task WITHOUT QA Scenarios is INCOMPLETE. No exceptions.**

- [ ] 1. [Task Title]

  **What to do**:
  - [Clear implementation steps]
  - [Test cases to cover]

  **Must NOT do**:
  - [Specific exclusions from guardrails]

  **Recommended Agent Profile**:
  - **Category**: \\\`[category]\\\`
    - Reason: [Why this category fits]
  - **Skills**: [\\\`skill-1\\\`, \\\`skill-2\\\`]
  - **Skills Evaluated but Omitted**:
    - \\\`omitted-skill\\\`: [Why not needed]

  **Parallelization**:
  - **Can Run In Parallel**: YES | NO
  - **Parallel Group**: Wave N
  - **Blocks**: [Tasks that depend on this]
  - **Blocked By**: [Tasks this depends on] | None

  **References** (CRITICAL - Be Exhaustive):
  - Pattern: \\\`src/path:lines\\\` — [what to follow and why]
  - API/Type: \\\`src/types/x.ts:TypeName\\\` — [contract]
  - Test: \\\`src/__tests__/x.test.ts\\\` — [testing patterns]
  - External: \\\`url\\\` — [docs reference]

  **Acceptance Criteria**:
  - [ ] [Verifiable condition with command]

  **QA Scenarios (MANDATORY):**
  \\\\\\\`\\\\\\\`\\\\\\\`
  Scenario: [Happy path]
    Tool: [Playwright / interactive_bash / Bash]
    Steps: [exact actions]
    Expected: [concrete pass/fail]
    Evidence: .groundcontrol/evidence/task-{N}-{slug}.{ext}

  Scenario: [Failure/edge case]
    Tool: [same]
    Steps: [trigger error]
    Expected: [graceful failure]
    Evidence: .groundcontrol/evidence/task-{N}-{slug}-error.{ext}
  \\\\\\\`\\\\\\\`\\\\\\\`

  **Commit**: YES | NO
  - Message: \\\`type(scope): desc\\\`
  - Files: \\\`path/to/file\\\`

---

## Final Verification Wave (MANDATORY)

> 4 review agents run in PARALLEL. ALL must APPROVE.

- [ ] F1. **Plan Compliance Audit** — oracle
- [ ] F2. **Code Quality Review** — unspecified-high
- [ ] F3. **Real Manual QA** — unspecified-high (+ playwright if UI)
- [ ] F4. **Scope Fidelity Check** — deep

---

## Commit Strategy
## Success Criteria
\\\`\\\`\\\`

---
`;
