/**
 * Groundcontrol Flight Plan Template
 *
 * The markdown template structure for flight plans
 * generated by Groundcontrol following NASA Flight Controller protocols.
 */

export const GROUNDCONTROL_PLAN_TEMPLATE = `## Flight Plan Structure

Generate flight plan to: \`.groundcontrol/plans/{name}.md\`

\\\`\\\`\\\`markdown
# FLIGHT PLAN: {Mission Title}

## MISSION OVERVIEW

> **Mission Type**: [Type-A Critical / Type-B Flight Ops / Type-C Recon / Type-D Support]
> **Classification**: [Official / Unofficial]
> **Flight Director**: [User name / Auto-authorized]
> **T-Minus**: [Timestamp]

---

## EXECUTIVE SUMMARY

### Mission Objective
> **Primary Objective**: [1-2 sentences defining what this mission achieves]
>
> **Success Criteria**:
> - [Verifiable condition with command]
> - [Verifiable condition with command]

### Deliverables
- [Exact file/endpoint/feature to deliver]
- [Verification artifact]

### Mission Profile
- **Estimated Duration**: [Quick | Short | Medium | Long | Extended]
- **Parallel Execution**: [YES - N waves | NO - sequential]
- **Flight Phases**: Phase 1 → Phase 2 → Phase 3 → Phase 4

---

## PHASE 1: REQUIREMENTS DEFINITION

> **Objective**: Establish mission parameters, success criteria, and constraints.

### Mission Requirements & Bi-Directional Traceability
> *NPR 7150.2D Mandate: All requirements must be traceable to design, implementation, and test.*
1. **[REQ-01]**: [Specification with measurable outcome] ➔ *Traces to:* [Planned Component/Test]
2. **[REQ-02]**: [Specification with measurable outcome] ➔ *Traces to:* [Planned Component/Test]
### Requirements Traceability Matrix (NASA-STD-8739.8B)
> *Every requirement must trace forward to implementation and test. If the user has no existing requirement IDs, auto-generate sequential IDs (e.g., REQ-001, REQ-002).*

| Req ID | Requirement Description | Design Component | Implementation | Test/Verification | Status |
|--------|------------------------|------------------|----------------|-------------------|--------|
| [REQ-001] | [Description] | [Component] | [File/Module] | [Test ID/Method] | [Open] |
| [REQ-002] | [Description] | [Component] | [File/Module] | [Test ID/Method] | [Open] |

> **Fallback**: If no external requirement IDs exist, Groundcontrol assigns sequential IDs (REQ-001..REQ-N) and traces them through to verification.

### Constraints & Boundaries
- **MUST HAVE**: [Non-negotiable requirements]
- **MUST NOT HAVE**: [Explicit exclusions from scope]
- **ASSUMPTIONS**: [Documented assumptions being made]

### Success Criteria (Phase Gate)
- [ ] Requirements documented and approved
- [ ] Traceability matrix populated (all REQs traced to design + test)
- [ ] Scope boundaries established
- [ ] Success metrics defined

---

## PHASE 2: HAZARD ANALYSIS & ARCHITECTURE

> **Objective**: Identify hazards, establish abort criteria, define system architecture following JPL Power of Ten principles.

### JPL Power of Ten Alignment
> *Where practical, incorporate these principles:*
> 1. Simplicity — Minimizes complexity and potential failure points
> 2. Separation — Isolates components for independent failure containment
> 3. Directness — Uses straightforward, traceable execution paths
> 4. Consistency — Maintains uniform interfaces and error handling
> 5. Reflexivity — Handles unexpected inputs gracefully
> 6. Observability — Provides clear state indication and logging
> 7. Recoverability — Enables clean rollback and state restoration
> 8. Maturity — Relies on battle-tested patterns, not novel approaches
> 9. Scrutability — Makes failure modes diagnosable
> 10. Frugality — Avoids unnecessary features and complexity

### Hazard Analysis & Software Risk Management
> *NPR 7150.2D Compliance: Software Risk Management*
| ID | Hazard Description | Severity | Probability | Mitigation Strategy | Abort Trigger | Recovery Path |
|----|-------------------|----------|-------------|---------------------|---------------|---------------|
| H1 | [Description] | [P1-Critical/P2-Major/P3-Minor] | [High/Med/Low] | [Strategy] | [Go/No-Go condition] | [Rollback procedure] |
| H2 | [Description] | [P1/P2/P3] | [High/Med/Low] | [Strategy] | [Condition] | [Rollback] |

### Abort & Adaptation Strategy
> **NOTE: MISSION RESILIENCE**
> Do not abort on the first failure. We expect to encounter errors, learn from them, and adapt.
> Only abort the mission if there are SIGNIFICANT DEVIATIONS from the plan required to solve the issue,
> or if an unrecoverable safety threshold is breached (NASA-STD-8739.8).

**Adaptation & Non-conformance Protocol** (How to handle normal failures / defects):
- **Test Failures**: Re-evaluate the implementation, fix the code, do not abort. Document the non-conformance.
- **Missing Minor Dependencies**: Find alternatives or workarounds. Document the deviation.
- **Integration Issues**: Isolate the component, verify interfaces, adapt the approach.

**Deviation Thresholds** (When to STOP and request re-planning):
- [ ] ABORT if the core architecture must be fundamentally changed
- [ ] ABORT if a critical dependency is entirely missing or incompatible
- [ ] ABORT if [Hazard ID] manifests and recovery is impossible
- [ ] ABORT if [Resource] is persistently unavailable

**Recovery Protocol**:
- Rollback to previous state: [Procedure]
- Estimated recovery time: [Duration]
- Data restoration: [Method]

### Architecture Decisions
- **Pattern Selected**: [Why this pattern]
- **Alternative Considered**: [Why rejected]
- **JPL Principles Applied**: [Which principles and how]

### Phase Gate Checkpoint
- [ ] All hazards identified and assessed
- [ ] Abort criteria established
- [ ] Recovery procedure verified
- [ ] **GO/NO-GO**: [PROCEED / HOLD]

---

## PHASE 3: IMPLEMENTATION (Flight Operations)

> **Objective**: Execute mission operations following established parameters.

### Mission Timeline

| Task | Description | Dependencies | Agent Profile | Parallel | Duration |
|------|-------------|--------------|---------------|----------|----------|
| 3.1 | [Task name] | [Dep] | [specialist] | [Y/N] | [Est] |
| 3.2 | [Task name] | [Dep] | [specialist] | [Y/N] | [Est] |
| 3.N | [Task name] | [Dep] | [specialist] | [Y/N] | [Est] |

### Implementation Detail

> **CRITICAL - PARALLEL EXECUTION PROTOCOL**: When executing tasks in parallel, executing agents MUST utilize \`git worktrees\` to prevent file conflicts, clobbering, and ensure clean integration. Each parallel task must isolate its changes in a dedicated worktree and merge back cleanly when verified.

#### Task 3.{N}: {Task Title}

**Objective**:
- [Clear implementation objective]

**Approach**:
- [Step 1]
- [Step 2]

**State Changes**:
- Files modified: [list]
- Data affected: [description]
- Services impacted: [list]

**Verification Requirements**:
- [ ] Unit tests pass
- [ ] Integration verification
- [ ] Manual QA scenarios executed

**Off-Nominal / Safety-Critical QA Scenarios (NASA-STD-8739.8B)**:
> *Identify edge cases, failure modes, and boundary conditions that could cause incorrect, unsafe, or degraded behavior.*
- [ ] **Boundary condition**: [Input at min/max/overflow] → Expected: [behavior]
- [ ] **Invalid input**: [Malformed/missing/null data] → Expected: [graceful handling]
- [ ] **Resource exhaustion**: [Memory/disk/network failure] → Expected: [degraded mode]
- [ ] **Concurrent access**: [Race condition scenario] → Expected: [safe resolution]
- [ ] **Recovery verification**: [After failure, system returns to known-good state]

**Phase Gate Checkpoint**:
- [ ] Implementation complete
- [ ] Self-verified
- [ ] **GO/NO-GO**: [PROCEED / HOLD / ABORT]

---

## PHASE 4: VERIFICATION & VALIDATION (V&V)

> **Objective**: Comprehensive verification that mission objectives were achieved safely.

### Verification Matrix

| Verification Type | Method | Acceptance Criteria | Status |
|-------------------|--------|---------------------|--------|
| Functional | [Test/Command] | [Criteria] | [Pending/Pass/Fail] |
| Integration | [Test/Command] | [Criteria] | [Pending/Pass/Fail] |
| Performance | [Benchmark] | [Threshold] | [Pending/Pass/Fail] |
| Safety | [Hazard Check] | [Criteria] | [Pending/Pass/Fail] |

### V&V Protocols

#### Protocol 4.1: Functional Verification
\`\`\`
Test: [Description]
Command: [Exact command to execute]
Expected: [Concrete pass/fail condition]
\`\`\`

#### Protocol 4.2: Safety Verification
\`\`\`
Check: [Hazard name from Phase 2]
Verification: [How we confirm hazard did not manifest]
Threshold: [Pass/fail boundary]
\`\`\`

#### Protocol 4.3: Simulation Credibility Assessment (NASA-STD-7009B) — CONDITIONAL
> *Include this section ONLY when the mission involves models, simulations, physics engines, ML inference pipelines, or any software whose outputs are used to inform real-world decisions.*

| Factor | Assessment | Evidence | Score (1-5) |
|--------|-----------|----------|-------------|
| Verification | [Code correctness proven?] | [Test results/review] | [1-5] |
| Validation | [Outputs match real-world data?] | [Comparison data] | [1-5] |
| Input Pedigree | [Input data quality/provenance?] | [Source documentation] | [1-5] |
| Results Uncertainty | [Uncertainty bounds quantified?] | [Analysis method] | [1-5] |
| Results Robustness | [Sensitivity to input variation?] | [Sensitivity tests] | [1-5] |

> **Credibility Threshold**: Score ≥ 3 in all factors for decision-support use. Flag any factor scoring ≤ 2 as a mission risk in the Hazard Analysis (Phase 2).

### Final Mission Certification

> **POST-FLIGHT ANALYSIS**

| Assessment | Rating | Notes |
|------------|--------|-------|
| Mission Objectives | [Achieved/Partial/Failed] | [Details] |
| Hazard Prevention | [Success/Issue/Failure] | [Details] |
| State Integrity | [Intact/Modified/Failed] | [Details] |
| Performance | [Within/Exceeded/Failed] | [Details] |

### Mission Outcome
- [ ] **MISSION SUCCESS**: All objectives achieved, no hazards manifested
- [ ] **MISSION PARTIAL**: Objectives mostly achieved, minor issues
- [ ] **MISSION FAILED**: Abort called or objectives not achieved
- [ ] **MISSION SCRUBBED**: Pre-flight abort, no execution

---

## FLIGHT LOG

| Event | Timestamp | Action | Result |
|-------|-----------|--------|--------|
| Mission Briefing Complete | T-XXX | Requirements defined | GO |
| Pre-Flight Go/No-Go | T-XXX | Hazard analysis complete | GO |
| Flight Phase 1 | T-XXX | Requirements approved | GO |
| Flight Phase 2 | T-XXX | Architecture verified | GO |
| Flight Phase 3 | T-XXX | Implementation complete | GO |
| Flight Phase 4 | T-XXX | V&V complete | [Result] |

---

## APPENDICES

### A: Rollback Procedures
\`\`\`
Command: [Exact rollback command]
Verification: [How to confirm rollback success]
\`\`\`

### B: Contact List
- **Flight Director**: [User]
- **Mission Control**: [System]
- **Recovery Team**: [Agent]

### C: Reference Documentation
- [Link to relevant docs]
- [Link to patterns followed]
\`\`\`

---
`;
